### ISSUE TITLE
Request response is empty

### ISSUE THREAD

**Issue by bhushan-borole** [rjruizfdez/instagram-user-id#1]
Python request response is empty, but works on browser.
Why?

**Comment by ricardojoserf** [comment]
Hello @bhushan-borole, i am searching why this happens but i do not find the answer. In the meantime, please tell me if you do :)

Best regards!

**Comment by ricardojoserf** [comment]
Hello @bhushan-borole !!!
Sorry i could not fix it until now! The Python script is working again, i changed the url because the previous one seems to have been banned, i do not know why :( 
But now it works, i hope you find it useful.
Best regards from Spain!
Ricardo

**Comment by ricardojoserf** [comment]
Hello, as the problem is solved and i did not receive an answer in one week, i will close the issue.
Thank you! :)
