### ISSUE TITLE
what is rank token

### ISSUE THREAD

**Issue by umeshdepale** [rjruizfdez/instagram-user-id#2]

**Comment by ricardojoserf** [comment]
Hi @umeshdepale . I am not sure, it seems it is a random token value used by the Instagram API.

Regards

**Comment by poria92** [comment]
Hi in         "mgp25/instagram-php": "^6.0",  package
you can simply use
`$rankToken=Signatures::generateUUID();`

**Comment by ricardojoserf** [comment]
Hi @poriazarei !!! I did this a long time ago but I think it does not use instagram-php, it is written in Python.

Regards!!
